name: Deploy to OCI VM	

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build Angular Project
      run: ng build --configuration production

    - name: Deploy to OCI VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.OCI_VM_IP }}
        username: ${{ secrets.OCI_VM_USER }}
        key: ${{ secrets.OCI_VM_SSH_PRIVATE_KEY }}
        port: 22
        source: "dist/sonidos-del-pura-vida/browser/*"
        target: "/var/www/html/sonidosPV"
