name: Deploy Backend to OCI VM

on:
  push:
    paths:
    - 'Backend/**'
    branches: [ main ]
  pull_request:
    paths:
    - 'Backend/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to OCI VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "./Backend/*"
        target: "/var/www/html/sonidosPV"